<nav id="navbar">
    <ul>
        <li id="index"><a href="index.php">Home</a></li>
        <li id="jobs"><a href="jobs.php">Jobs</a></li>
        <li id="apply"><a href="apply.php">Apply</a></li>
        <li id="about"><a href="about.php">About</a></li>
        <li id="manage"><a href="manage.php">Manage</a></li>
        <li id="login"><a href="login.php">Login</a></li>
        <li id="register"><a href="register.php">Register</a></li>
        <li id="enhancements"><a href="enhancements.php">Enhancements</a></li>
        <li id="enhancements2"><a href="enhancements2.php">Enhancements2</a></li>
        <li id="phpenhancements"><a href="phpenhancements.php">PHPEnhancements</a></li>
    </ul>
</nav>